<a href="https://colab.research.google.com/github/navyasreeg2025-bot/eda-lab-experiment/blob/main/28-07-2026_handlingmissingvalues.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd
import numpy as np

data = np.arange(10, 25).reshape(5, 3)
df = pd.DataFrame(data,index=['Raj','Priya','Amit','Sara','Neha'],columns=['Math','Science','English'])

In [18]:
df['History'] = np.nan
df.loc['Kiran'] = [10,11,12,13, np.nan]
df.loc['Vikas'] = np.nan
df['Geography'] = np.nan
df.loc['Raj','History'] = 15
print(df)
print(df.columns)

       Math  Science  English  History  Geography
Raj    10.0     11.0     12.0     15.0        NaN
Priya  13.0     14.0     15.0      NaN        NaN
Amit   16.0     17.0     18.0      NaN        NaN
Sara   19.0     20.0     21.0      NaN        NaN
Neha   22.0     23.0     24.0      NaN        NaN
Kiran  10.0     11.0     12.0     13.0        NaN
Vikas   NaN      NaN      NaN      NaN        NaN
Index(['Math', 'Science', 'English', 'History', 'Geography'], dtype='object')

In [21]:
df.dropna()
df.dropna(how='all')
df.dropna(how='all', axis=1)
df.dropna(thresh=5, axis=1)

       Math  Science  English
Raj    10.0     11.0     12.0
Priya  13.0     14.0     15.0
Amit   16.0     17.0     18.0
Sara   19.0     20.0     21.0
Neha   22.0     23.0     24.0
Kiran  10.0     11.0     12.0
Vikas   NaN      NaN      NaN

In [33]:
filledDf = df.fillna(0)
df.History.fillna(method='ffill')
df.History.fillna(method='bfill')

/tmp/ipykernel_704/894065789.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.History.fillna(method='ffill')
/tmp/ipykernel_704/894065789.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.History.fillna(method='bfill')

Raj      15.0
Priya    13.0
Amit     13.0
Sara     13.0
Neha     13.0
Kiran    13.0
Vikas     NaN
Name: History, dtype: float64

In [24]:
df.History.sum()
df.History.mean()
df.History.cumsum()

Raj      15.0
Priya     NaN
Amit      NaN
Sara      NaN
Neha      NaN
Kiran    28.0
Vikas     NaN
Name: History, dtype: float64

In [25]:
df.isnull()

        Math  Science  English  History  Geography
Raj    False    False    False    False       True
Priya  False    False    False     True       True
Amit   False    False    False     True       True
Sara   False    False    False     True       True
Neha   False    False    False     True       True
Kiran  False    False    False    False       True
Vikas   True     True     True     True       True

In [26]:
df.notnull()

        Math  Science  English  History  Geography
Raj     True     True     True     True      False
Priya   True     True     True    False      False
Amit    True     True     True    False      False
Sara    True     True     True    False      False
Neha    True     True     True    False      False
Kiran   True     True     True     True      False
Vikas  False    False    False    False      False

In [31]:
df.isnull().sum()

Math         1
Science      1
English      1
History      5
Geography    7
dtype: int64

In [32]:
df.isnull().sum().sum()

np.int64(15)